### ISSUE TITLE
Make navbar responsive on mobile/desktop

### ISSUE THREAD

**Issue by alvarotorrestx** [rvalde28/restaurant#3]
Navbar should wrap or create hamburger menu with cart icon visible

Current view on mobile:
![image](https://github.com/user-attachments/assets/beaa0e0b-9cf0-49a7-b20d-4386b8cab927)

**Comment by rvalde28** [comment]
So with this one, i plan on not having a nav bar at the top. I instead want the menu/nav to be at the bottom. kind of like this: 

![image](https://github.com/user-attachments/assets/ddb08204-a307-4957-8a8d-430430702e41)

**Comment by rvalde28** [comment]
for sure is an issue right now :(

**Comment by alvarotorrestx** [comment]
This can be done, I'll get started asap on this too! @rvalde28 👌

**Comment by alvarotorrestx** [comment]
Updated the most recent commit, sir. @rvalde28
