### ISSUE TITLE
Clean up Menu items

### ISSUE THREAD

**Issue by alvarotorrestx** [rvalde28/restaurant#4]
Menu items need to be consistent and have more spacing on smaller screen sizes

Mobile:
![image](https://github.com/user-attachments/assets/595652a2-cbc6-483a-9b55-5c97483fcd30)

![image](https://github.com/user-attachments/assets/131f3ff7-c1d1-4659-bdf4-12a0f80e7908)

Tablet:
![image](https://github.com/user-attachments/assets/a7747f69-3c7b-4c8c-9d98-0b1b3fac3a46)

**Comment by rvalde28** [comment]
YES!!! was trying to see how to fix this using the taiwind css properties but it seems like it needs some tuning so that it scales properly

**Comment by alvarotorrestx** [comment]
@rvalde28 I got you, my man 😎
